---
# vars file for defilan-macos

homebrew_taps:
- hashicorp/tap
- homebrew/cask-fonts
- aws/tap

homebrew_packages:
- neovim
- tmux
- git-extras
- thefuck
- neovim
- go
- kubectl
- skaffold
- awscli
- hashicorp/tap/terraform
- hashicorp/tap/packer
- aws-sam-cli
- node

homebrew_cask_packages:
- google-chrome
- iterm2
- visual-studio-code
- spotify
- 1password
- rectangle
- font-hack-nerd-font
- slack
- jetbrains-toolbox
- nordvpn
- zoom
- microsoft-office
- evernote
- microsoft-remote-desktop
- switchresx
- discord
- istat-menus
- signal
- docker
- postman
