---
# vars file for defilan-macos

config_packages:
  config1:
    homebrew_cask_packages:
      - arc
      - iterm2
      - 1password
      - rectangle
      - istat-menus
  config2:
    homebrew_taps:
      - hashicorp/tap
      - homebrew/cask-fonts
      - aws/tap
    homebrew_packages:
      - neovim
      - tmux
      - git-extras
      - thefuck
      - go
      - kubectl
      - skaffold
      - awscli
      - hashicorp/tap/terraform
      - hashicorp/tap/packer
      - aws-sam-cli
      - node
      - redis
      - molecule
    homebrew_cask_packages:
      - arc
      - iterm2
      - visual-studio-code
      - 1password
      - rectangle
      - font-hack-nerd-font
      - jetbrains-toolbox
      - switchresx
      - istat-menus
      - docker
      - postman
      - obs
  config3:
    homebrew_taps:
      - hashicorp/tap
      - homebrew/cask-fonts
      - aws/tap
    homebrew_packages:
    - neovim
    - tmux
    - git-extras
    - thefuck
    - go
    - kubectl
    - skaffold
    - awscli
    - hashicorp/tap/terraform
    - hashicorp/tap/packer
    - aws-sam-cli
    - node
    - redis
    - molecule
  homebrew_cask_packages:
    - arc
    - iterm2
    - visual-studio-code
    - 1password
    - rectangle
    - font-hack-nerd-font
    - jetbrains-toolbox
    - nordvpn
    - switchresx
    - discord
    - istat-menus
    - signal
    - docker
    - postman
    - gimp
    - obs
    - krisp
    - microsoft-office

defilan_directories:
- ~/stuffy
- ~/stuffy/code
- ~/stuffy/playground