---
# tasks file for defilan-macos

- name: Set config variable
  set_fact:
    config: "{{ lookup('env', 'config') }}"

- name: Add Extra Casks
  community.general.homebrew_tap:
    name: "{{ item }}"
  loop: "{{ config_packages[config].homebrew_taps }}"
  when: config_packages[config].homebrew_taps is defined

- name: Install brew packages 
  homebrew:
    name: "{{ item }}"
  loop: "{{ config_packages[config].homebrew_packages }}"
  when: config_packages[config].homebrew_packages is defined

- name: Install cask packages
  homebrew_cask:
    name: "{{ item }}"
  loop: "{{ config_packages[config].homebrew_cask_packages }}"
  when: config_packages[config].homebrew_cask_packages is defined


- name: Create stuffy directory
  file:
    path: "{{ ansible_env.HOME }}/stuffy"
    state: directory

- name: Create subdirectories
  file:
    path: "{{ ansible_env.HOME }}/stuffy/{{ item }}"
    state: directory
  loop:
    - code
    - playground

- name: Installing oh-my-zsh
  git:
    repo: "https://github.com/robbyrussell/oh-my-zsh.git"
    dest: "{{ ansible_env.HOME + '/.oh-my-zsh' }}"
    update: yes
  register: defilan_macos_git_result
  changed_when: "defilan_macos_git_result.after|default('after') != defilan_macos_git_result.before|default('before')"

- name: Configuring oh-my-zsh
  template:
    src: ".zshrc.j2"
    dest: "{{ ansible_env.HOME + '/.zshrc' }}"
    backup: yes

- name: Installing ZSH Autosuggestion
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "{{ ansible_env.HOME + '/.oh-my-zsh/custom/plugins/zsh-autosuggestions' }}"