name: Ansible Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ansible-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Lint
        uses: azohra/shell-linter@latest
        with:
          path: "install.sh,install"